### ISSUE TITLE
repeating code in "report - naive one.r"

### ISSUE THREAD

**Issue by MichaelFolkes** [avelez-espino/forecastR_phase4#12]
I think all code in the aforementioned script is doubled. I found there were two functions that were exact copies and same name too. then started looking at the code and I think it's all doubled, as if she copied and pasted twice into the file. I've removed the functions but not changed the script.

**Comment by SOLV-Code** [comment]
in *Report - Naive One_functions.r*, there are two functions called *empirical.probability.yboot.naiveone.total.age*. Based on your note above, I assume these are identical. 
Either way, the second one overwrites the first, so I've excluded the first version.
