### ISSUE TITLE
referencing objects inside functions

### ISSUE THREAD

**Issue by MichaelFolkes** [avelez-espino/forecastR_phase4#27]
Inside functions, there are countless reference to list objects that were not arguments to the function.
eg: 
https://github.com/avelez-espino/forecastR_phase4/blob/a9e2358431cafdb1042bf2ab0404bfe76e43ce34/R/SIMPLESIBREG/RETRO%20-%20Simple%20Sibling%20Regression_functions.r#L5

I assume we should try to make those objects arguments to the function.

**Comment by SOLV-Code** [comment]
Yes. I have been doing that for the n1 functions whenever n1$something was causing the function to crash....
